SET HEADING OFF
SET FEEDBACK OFF
SET UNDERLINE OFF
SET PAGESIZE 0
SET LINESIZE 1000
SET LONG 50000
SET LONGCHUNKSIZE 50000

BEGIN
    -- LOBストレージ情報を出力しないように設定
    DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'STORAGE', FALSE);
    -- LOBのセグメント属性も出力しないように設定
    DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'SEGMENT_ATTRIBUTES', FALSE);
END;
/

spool output_ddl.log

SELECT REGEXP_REPLACE(
    DBMS_METADATA.GET_DDL('SEQUENCE', 'SEQ_T_LOB_DETAIL', 'PDBUSER'), 
    'START WITH \d+', 
    'START WITH 1'
) || ';'
FROM DUAL
/
SELECT DBMS_METADATA.GET_DDL('TABLE', 'T_LOB_HEADER', 'PDBUSER') || ';' FROM DUAL
/
SELECT DBMS_METADATA.GET_DDL('INDEX', 'CTX1_T_LOB_HEADER', 'PDBUSER') || ';' FROM DUAL
/
SELECT DBMS_METADATA.GET_DDL('TABLE', 'T_LOB_DETAIL', 'PDBUSER') || ';' FROM DUAL
/
SELECT DBMS_METADATA.GET_DDL('INDEX', 'IDX1_T_LOB_HEADER', 'PDBUSER') || ';' FROM DUAL
/
SELECT DBMS_METADATA.GET_DDL('INDEX', 'IDX2_T_LOB_HEADER', 'PDBUSER') || ';' FROM DUAL
/
SELECT DBMS_METADATA.GET_DDL('INDEX', 'CTX1_T_LOB_DETAIL', 'PDBUSER') || ';' FROM DUAL
/

spool off