CREATE OR REPLACE PROCEDURE PR_INSERT_LOB_HEADER(p_entities IN T_LOB_HEADER_ARRAY) IS
BEGIN
  FORALL i IN 1 .. p_entities.COUNT
    INSERT INTO T_LOB_HEADER (ID, TEXT, TEXT_LEN, FRAGMENT_COUNT)
    VALUES (p_entities(i).ID, p_entities(i).TEXT, p_entities(i).TEXT_LEN, p_entities(i).FRAGMENT_COUNT);
  COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM);
    ROLLBACK;
    RAISE;
END;
/

