DROP TYPE T_LOB_HEADER_ARRAY
/

-- オブジェクトタイプを作成
CREATE OR REPLACE TYPE T_LOB_HEADER_OBJ AS OBJECT (
  ID NUMBER,
  TEXT CLOB,
  TEXT_LEN NUMBER,
  FRAGMENT_COUNT NUMBER
)
/

-- テーブルタイプを作成
CREATE TYPE T_LOB_HEADER_ARRAY IS TABLE OF T_LOB_HEADER_OBJ
/

exit;