-- PDBへ切り替え
ALTER SESSION SET CONTAINER=ORAPDB1;

-- ユーザ削除
DROP USER PDBUSER CASCADE;

-- ユーザ作成
CREATE USER PDBUSER IDENTIFIED BY oracle
DEFAULT TABLESPACE USERS
QUOTA UNLIMITED ON USERS
TEMPORARY TABLESPACE TEMP;

-- 作成ユーザへ権限付与
GRANT DBA TO PDBUSER;
-- GRANT CREATE SESSION TO PDBUSER;
-- GRANT RESOURCE TO PDBUSER;
-- GRANT UNLIMITED TABLESPACE TO PDBUSER;